workflows:
  ios-fastlane:
    name: Build e Testes com Fastlane
    max_build_duration: 60
    environment:
      xcode: 15.2
      cocoapods: default
      vars:
        FL_BUILD_PLATFORM: ios
    scripts:
      - name: Instalar dependências
        script: |
          bundle install || gem install bundler && bundle install
      - name: Mostrar conteúdo do project.pbxproj
        script: |
          echo "Conteúdo de GalaxyMovies.xcodeproj/project.pbxproj:"
          cat GalaxyMovies.xcodeproj/project.pbxproj
      - name: Rodar Fastlane
        script: |
          bundle exec fastlane build_and_test || fastlane build_and_test
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
    artifacts:
      - build/**/*.ipa
      - build/**/fastlane/test_output/**/*
