name: Build & Test iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-13 # ou macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Build project
        run: |
          xcodebuild \
            -project GalaxyMovies.xcodeproj \
            -scheme GalaxyMovies \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            clean build

      - name: Run tests
        run: |
          xcodebuild \
            -project GalaxyMovies.xcodeproj \
            -scheme GalaxyMovies \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            test
