name: CI - Build e Testes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: macos-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Ruby (usado pelo Fastlane)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # ou a versão que você usa localmente

      - name: Instalar dependências do bundler (se usar Gemfile)
        run: bundle install
        if: exists('Gemfile')

      - name: Instalar Fastlane
        run: |
          gem install fastlane --no-document
        if: steps.bundle.outputs.cache-hit != 'true'

      - name: Rodar Fastlane
        run: bundle exec fastlane build_and_test
        # ou, se não usar bundler:
        # run: fastlane build_and_test
