jobs:
  build_and_test:
    runs-on: macos-14
    defaults:
      run:
        shell: bash
    steps:
      - name: Selecionar Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Instalar dependências do bundler (se usar Gemfile)
        run: |
          if [ -f Gemfile ]; then
            bundle install
          fi

      - name: Instalar Fastlane
        run: |
          gem install fastlane --no-document

      - name: Rodar Fastlane
        run: |
          if [ -f Gemfile ]; then
            bundle exec fastlane build_and_test
          else
            fastlane build_and_test
          fi
